### ISSUE TITLE
Add support for multiple languages.

### ISSUE THREAD

**Issue by bascht** [bnbeckwith/writegood-mode#17]
Thanks for creating this mode! I like it a lot and would try to add support for the German language. I'm not too firm with elisp, but from what I've seen I'd only have to supply `writegood-passive-voice-irregulars` and `writegood-weasel-words` to fully support another language.

If those two variables would exist in a hash-like data structure, I could supply a pull request that would add German.

**Comment by bnbeckwith** [comment]
@bascht, the `writegood-weasel-words` could be overridden/appended with any words of your choice.   For example, you can add "foobar" with the following code:

```elisp
(add-to-list writegood-weasel-words "foobar")
```

It's also available through the 'customize' interface in Emacs.

The passive-voice irregulars are more difficult. In the code, they are prepended by the various forms of  the English infinitive "to be".  This ties the source to English.  Do you have something similar in German? What sort of patterns would you want to catch that are different from weasel-words?

**Comment by tommyskg** [comment]
I would be interested in multi-language support as well, more specifically for Norwegian.

As far as I can tell much of the plugin structure and content are directly related to English. Thus, e.g. the FK-test does not apply to other languages I presume. Would it be possible to restructure it to be more modular, and then again have some kind of pattern, readability scoring etc interface for each language module?

I think this will make it easier to go with the next step of implementing the other language modules instead of hacking the existing library.

Ftr I reached out to The Language Council of Norway and they referred me to a weasel word equivalent list located at https://www.sprakradet.no/Klarsprak/skrivehjelp/Skriverad/Kutt-kansellistilen/soek-i-kansellisten/

**Comment by bnbeckwith** [comment]
I believe the only english-specific check is that of the passive voice. The two other checks should be compatible with most languages.  Duplicates are easy and *should* be language-agnostic.  For the weasel-words, I simply leverage a list of words to avoid and highlight those. Supplying additional words should enable this for any language.

As for the reading checks, they are certainly language specific. I'm happy to look over any pull requests for checks for additional languages.
